name: HW06_promocode
services:
  promocode-factory-api:
    build:
      context: .
    container_name: 'promocode-factory-api'
    restart: always
    ports:
      - "8091:8080"
    volumes:
      - db:/app/db
    environment:
      - "ConnectionStrings:PromocodeFactoryDb=Filename=/app/db/PromoCodeFactoryDb.sqlite"
      - "ASPNETCORE_ENVIRONMENT=Development"

volumes:
  db:
