name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    name: UnitTests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
          cache: false

      - name: Restore
        working-directory: Homeworks/UnitTests/src
        run: dotnet restore PromoCodeFactory.sln

      - name: Test
        working-directory: Homeworks/UnitTests/src
        run: dotnet test PromoCodeFactory.sln -c Release --no-restore

