# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Run Unit Tests

on:
  push:
    branches: [ "CRUD_branch" ]
  pull_request:
    branches: [ "CRUD_branch" ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore PromoCodeFactory.sln

    - name: Build solution
      run: dotnet build PromoCodeFactory.sln --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test PromoCodeFactory.sln --configuration Release --no-build --verbosity normal
